### ISSUE TITLE
DonnerPlays CPAP 7040 part cooling solution Github link broke

### ISSUE THREAD

**Issue by guitartoys** [MarvinBeym/HevORT-Mods#3]
Pretty much as the subject line says, when you click the github link for Donnerplays fancy schmancy CPAP cooling jank, the link's broke.

**Comment by MarvinBeym** [comment]
Wrong repo => https://github.com/MirageC79/HevORT


My links works fine. MirageC changed all paths containing ``mods`` to ``Mods`` because he is a maniac.

Looks like he didn't make sure everything still worked
